name: PR Check Runner

on: 
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        python_version: ["3.11"]
    steps:
        - uses: actions/checkout@v4

        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install pytest

        - name: Lint with ruff
          run: |
            source venv/bin/activate
            python3 -m ruff check .

        - name: Check formatting with ruff
          run: |
            source venv/bin/activate
            python3 -m ruff format --check .

        - name: Run pytest
          run: |
            source venv/bin/activate
            pytest test/
